[package]
name = "typed_perm_derive"
version = "0.1.0"
authors = ["Valerian Garleanu <valerian.garleanu@pm.me>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.7"
syn = "1.0.31"
proc-macro2 = "1.0.18"
